server:
  port: 8080

jwt:
  secret: ${JWT_SECRET_KEY}
# 5시간
  access-token-time: 18000000
# 30일
  refresh-token-time: 2592000000
spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ENDPOINT}:3306/homecook
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    s3:
      bucket: homecook-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

fcm:
  key:
    path: homecook-fcm.json
    scope: https://www.googleapis.com/auth/cloud-platform